services:
  oficina-manager-app:
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: oficina-manager-app
    ports:
      - "5173:5173"
    working_dir: /var/www
    volumes:
      - ../../:/var/www
    networks:
      - oficina-manager

  oficina-manager-nginx:
    image: nginx:alpine
    container_name: oficina-manager-nginx
    ports:
      - "4500:80"
    volumes:
      - ../../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - oficina-manager-app
    networks:
      - oficina-manager

  oficina-manager-db:
    image: postgres:15-alpine
    container_name: oficina-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: dev_tentant
    ports:
      - "4501:5432"
    volumes:
      - ./db_data:/var/lib/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - oficina-manager

  oficina-manager-mail-server:
    image: 'axllent/mailpit:latest'
    container_name: oficina-manager-mail-server
    ports:
      - '4502:1025'
      - '4503:8025'
    networks:
      - oficina-manager

networks:
  oficina-manager:
